<?php
namespace Man;

class Father
{
    /**
     * @var string
     */
    private $name = '';
    /**
     * @var int
     */
    private $age  = 0;
    /**
     * @var string
     */
    private $sex  = '女';

    /**
     * Father constructor.
     * @param string $name
     */
    public function __construct($name)
    {
        $this->name = $name;
    }

    /**
     * @param int
     * @return string
     */
    public function test1()
    {
        echo 'test1';
    }
    public function test2()
    {
        echo 'test2';
    }

}
class Son extends Father
{
    public function test1()
    {
        parent::test1(); // TODO: Change the autogenerated stub
    }
}